name: login_flutter
description: A flutter login model app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
#  flutter_osm_plugin: ^1.0.3
  # geolocator: ^8.0.0
  geolocator: ^13.0.1  # Hoặc phiên bản mới nhất
  permission_handler: ^10.2.0  # Thêm dòng này
  firebase_core: ^3.5.0
  firebase_auth: ^5.0.0
  pigeon: ^22.4.0
  mqtt_client: ^10.5.0
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
